### ISSUE TITLE
[Bug]: First search returns no results, always have to search twice

### ISSUE THREAD

**Issue by bobbintb** [uniget-org/cli#353]
### What happened?

Whenever I use the Discover Packages search, it always comes back with no results, initially. I have to hit the search button again for it to show anything.

### Version

3.1.1

### What distribution are you seeing the problem on?

Windows 11

### Relevant output

```Shell
n/a
```

**Comment by nicholasdille** [comment]
I guess you wanted to report this in the unigetui project: https://github.com/marticliment/UniGetUI

**Comment by bobbintb** [comment]
> I guess you wanted to report this in the unigetui project: https://github.com/marticliment/UniGetUI

lol, omg, yes. Sorry about that. That's what I get for having a million tabs open!
